/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author qiwan7383
 */
public class yearsandeventsGUI extends javax.swing.JFrame {
    

    /**
     * Creates new form yearsandeventsGUI
     */
    public yearsandeventsGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        yearInputLabel = new javax.swing.JTextField();
        SearchButton = new javax.swing.JButton();
        reminder = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        OutputLabel = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 23)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 0));
        jLabel1.setText("20th Century Candian events search");

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 0));
        jLabel2.setText("Enter the Year:");

        yearInputLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearInputLabelActionPerformed(evt);
            }
        });

        SearchButton.setForeground(new java.awt.Color(255, 51, 0));
        SearchButton.setText("Search");
        SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButtonActionPerformed(evt);
            }
        });

        reminder.setForeground(new java.awt.Color(255, 102, 0));
        reminder.setText("(ONLY 20TH CENTURY )");

        OutputLabel.setColumns(20);
        OutputLabel.setRows(5);
        jScrollPane1.setViewportView(OutputLabel);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 3, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(yearInputLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addComponent(SearchButton))
                            .addComponent(jLabel1))
                        .addGap(86, 86, 86))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(reminder)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yearInputLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(SearchButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(reminder)
                .addGap(39, 39, 39)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setForeground(new java.awt.Color(255, 255, 255));

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButtonActionPerformed
       String year ;
     
     
       year = yearInputLabel.getText();
     
    
     
     if (year.equals("1900")){
     
       OutputLabel.setText("Federal immigration policy entices Eastern Europeans to Canadian West");
        }  else if (year.equals("1901")) { 
       OutputLabel.setText("Marconi receives the first transatlantic radio message at St. John’s, Newfoundland");
         
        }  else if (year.equals("1902")) {   
        OutputLabel.setText("Nothing");
        }  else if (year.equals("1903")) {
        OutputLabel.setText("Canada loses Alaska Boundary dispute when British representative sides with U.S."); 
        }   else if (year.equals("1904")) {
        OutputLabel.setText("Nothing");
        } else if (year.equals("1905")) {
        OutputLabel.setText("Provinces of Saskatchewan and Alberta are formed");
        } else if (year.equals("1906")) {
        OutputLabel.setText("Ontario Hydro Created:\n"+"The Hydro-Electric Power Commission of Ontario was created, with Adam Beck as chairman. It was the first publicly owned electric utility in the world.");
        }else if (year.equals("1907")) {
        OutputLabel.setText("Industrial Disputes Investigation Act (IDIA) requires compulsory conciliation of labour disputes");
        }else if (year.equals("1908")) { 
        OutputLabel.setText("Nothing");
        }else if (year.equals("1909")) {
        OutputLabel.setText("Nothing");
        }else if (year.equals("1910")) {
        OutputLabel.setText("Federal government decides to establish the Royal Canadian Navy");
        }else if (year.equals("1911")) {
        OutputLabel.setText("Liberal government of Wilfred Laurier loses Reciprocity election; Robert Borden becomes Prime Minister");
        }else if (year.equals("1912")) {
         OutputLabel.setText("S.S. Titanic sinks off Newfoundland; recovered bodies are buried in Halifax cemetery");
        }else if (year.equals("1913")) {
         OutputLabel.setText("Canadian economy goes into a slump");
        }else if (year.equals("1914")) {
       OutputLabel.setText("Canada automatically enters First World War when Britain declares war on Germany (August 4)");
        }else if (year.equals("1915")) {
        OutputLabel.setText("Nothing");
         }else if (year.equals("1916")) {
        OutputLabel.setText("Nothing");
         }else if (year.equals("1917")) {
        OutputLabel.setText("1.French munitions ship Mont Blanc catches fire and explodes in Halifax harbor on December 6th; 2,000 killed\n"+
                
                "2.Canadians capture Vimy Ridge after British and French attempts fail\n"+
                "3.Income tax is introduced by the federal government as a “temporary wartime measure”");
         }else if (year.equals("1918")) {    
         OutputLabel.setText("Under the War Measures Act, manufacture and sale of intoxicating beverages is prohibited in Canada");
         } else if (year.equals("1919")) {
        OutputLabel.setText("The Winnipeg General Strike began when the Winnipeg Trades and Labor Council called a general strike in sympathy with the strikers of May 1. The strike exposed the bitter class divisions in Canadian society and lasted seven weeks.");
         } else if (year.equals("1920")) {
        OutputLabel.setText("With passage of the Volstead Act in the United States, the rum-running era begins");
        } else if (year.equals("1921")) {
           OutputLabel.setText("Nothing");
        }else if (year.equals("1922")) {
          OutputLabel.setText("Foster Hewitt makes the world’s first radio broadcast of a hockey");
          }else if (year.equals("1923")) {
               OutputLabel.setText("Canada deals directly with U.S. without British participation in signing Halibut Treaty");
          }else if (year.equals("1924")) {
        OutputLabel.setText("Nothing");
          }else if (year.equals("1925")) {
        OutputLabel.setText("Delegation of Maritime businessmen and politicians travels to Ottawa to lobby for Maritime Rights");
         }else if (year.equals("1926")) {
         OutputLabel.setText("Old age pension instituted by federal government");
         }else if (year.equals("1927")) {
        OutputLabel.setText("Nothing");
        }else if (year.equals("1928")) {
            OutputLabel.setText("Supreme Court of Canada rules that women are not “persons” who can be elected to public office");
        }else if (year.equals("1929")) {
     OutputLabel.setText("1.British Privy Council overrules Supreme Court “non-person” decision\n"+
             "2.New York Stock Market crash");
     }else if (year.equals("1930")) {
         OutputLabel.setText("Nothing");
     } else if (year.equals("1931")) {
     OutputLabel.setText("Statute of Westminster grants Canada full autonomy from Britain\n"+
             "2.Female worker at Ganong’s candy factory in St. Stephen, N.B., makes $14/wk; her male foreman makes $32/wk");
     } else if (year.equals("1932")) {
      OutputLabel.setText("CCF found\n"+"The Co-operative Commonwealth Federation was founded in Calgary. Led by J.S. Woodsworth, the CCF was the first major democratic socialist movement in Canada and went on to have a profound effect on the Canadian political landscape."); 
     } else if (year.equals("1933")) {
     OutputLabel.setText("Newfoundland assembly votes to suspend self-government british appoint commission of government");
     }else if (year.equals("1934")) {
          OutputLabel.setText("The Dionne quintuplets are born in Callander, Ontario");
     }else if (year.equals("1935")) {
       OutputLabel.setText("R.B. Bennett’s New Deal for Canada announced; Supreme Court later declares it ultra vires"); 
     }else if (year.equals("1936")) {
      OutputLabel.setText("Nothing");
     }else if (year.equals("1937")) {
      OutputLabel.setText("Nothing");
     }else if (year.equals("1938")) {
     OutputLabel.setText("Nothing");
     }else if (year.equals("1939")) {
     OutputLabel.setText("Canada enters World War II after remaining neutral for 1 week; pro-war party in Québec wins provincial election");
     }else if (year.equals("1940")) {
     OutputLabel.setText("Ogdensburg agreement co-ordinates industrial output of Canada and U.S");
     }else if (year.equals("1941")) {
         OutputLabel.setText("Nothing");
     }else if (year.equals("1942")) {
      OutputLabel.setText("1.Construction boom due to American and Canadian military bases eliminates unemployment in Newfoundland\n"+
              "2.Canadian raid on French port of Dieppe is a disaster; British later claim it was useful rehearsal for D-Day\n"+
              "3.Japanese Relocation\n"+"The federal government announced that all people of Japanese origin living in the coastal regions of British Columbia would be relocated to the BC interior or inland farming areas.");;
     } else if (year.equals("1943")) {
         OutputLabel.setText("Nothing");
     }else if (year.equals("1944")) {
         OutputLabel.setText("1.Canadian troops advance further inland than any other Allied unit on D-Day (June 6)\n"+
                 "2.Saskatchewan voters elect the first socialist government in North America, led by Tommy Douglas");
     } else if (year.equals("1945")) {
          OutputLabel.setText("Nothing");
     }else if (year.equals("1946")) {
     OutputLabel.setText("Nothing");
     }else if (year.equals("1947")) {
      OutputLabel.setText("Nothing");
     }else if (year.equals("1948")) {
      OutputLabel.setText("Nothing");
     }else if (year.equals("1949")) {
      OutputLabel.setText("Newfoundland becomes Canada’s tenth province on March 31st");
     }else if (year.equals("1950")) {
      OutputLabel.setText("Pipeline Completed : The 1770 km oil pipeline from Edmonton to the Great Lakes was completed, linking Canada's gas fields with the markets of central Canada. In 1958 Alberta gas finally reached Toronto and imports of Texas gas ended.");
     }else if (year.equals("1951")) {
     OutputLabel.setText("1.Mid-century census records Canada’s population as 14 million\n"+
             "2.Royal Commission (Massey) reports that Canadian culture is dominated by American influences");
     }else if (year.equals("1952")) {
       OutputLabel.setText("First television stations in Canada begin broadcasting in Montreal (Sept. 6th) and Toronto (Sept. 8th)");  
     }else if (year.equals("1953")) {
      OutputLabel.setText("Nothing");
     }else if (year.equals("1954")) {
      OutputLabel.setText("Nothing");
         }else if (year.equals("1955")) {
         OutputLabel.setText("Montreal Canadiens hockey star Maurice “Rocket” Richard is suspended for fighting; riots break out in Montreal");
      }else if (year.equals("1956")) {
      OutputLabel.setText("Nothing");
      }else if (year.equals("1957")) {
          OutputLabel.setText("Nothing");
         }else if (year.equals("1959")) {
         OutputLabel.setText("St. Lawrence Seaway opens");
       }    else if (year.equals("1960")) {
         OutputLabel.setText("“Quiet Revolution” begins in Québec");
   }    else if (year.equals("1961")) {
        OutputLabel.setText("Nothing");
    }    else if (year.equals("1962")) {
     OutputLabel.setText("Trans-Canada Highway officially opens");
   }    else if (year.equals("1963")) {
       OutputLabel.setText("Nothing");
     }    else if (year.equals("1964")) {   
       OutputLabel.setText("New Flag Adopted:\n"+"A new national flag of Canada was adopted after much debate. The Senate gave its approval on 17 December.\n"+" Queen Elizabeth signed the royal proclamation on 28 January and the new flag, with its red maple leaf and side bars, flew officially for the first time on 15 February 1965.");
        }    else if (year.equals("1965")) {  
       OutputLabel.setText("1. The Auto Pact, forerunner of NAFTA, is signed between United States and Canada\n"+
               "2. Groundfish landings in Northwest Atlantic peak at 2.8 million tons");
        }    else if (year.equals("1966")) {  
        OutputLabel.setText("Nothing");
        }    else if (year.equals("1967")) {  
        OutputLabel.setText("Nothing");
        }    else if (year.equals("1968")) {  
        OutputLabel.setText("Nothing");
       }    else if (year.equals("1969")) {  
        OutputLabel.setText("The federal government becomes officially bilingual");
        }    else if (year.equals("1970")) {  
        OutputLabel.setText("The FLQ, a militant separatist group in Québec, kidnaps British diplomat and murders Québec cabinet minister");
        }    else if (year.equals("1971")) {  
        OutputLabel.setText("Nothing");
        }    else if (year.equals("1972")) {  
        OutputLabel.setText("Nothing");
       }    else if (year.equals("1973")) {  
        OutputLabel.setText("Nothing");
        }    else if (year.equals("1974")) {  
        OutputLabel.setText("Nothing");
         }    else if (year.equals("1975")) {  
        OutputLabel.setText("Nothing");
         }    else if (year.equals("1976")) {  
        OutputLabel.setText("1.Canada announces 200-nautical-mile coastal fishing zone\n"+"2.Parti Quebécois under Rene Levesque wins Québec provincial election on separatist platform");
          }    else if (year.equals("1977")) {  
        OutputLabel.setText("Nothing");
         }    else if (year.equals("1978")) {  
        OutputLabel.setText("Nothing");
           }    else if (year.equals("1979")) {  
        OutputLabel.setText("Nothing");
           }    else if (year.equals("1980")) {  
        OutputLabel.setText("1.The majority of Québecers reject separation from Canada in a referendum vote\n"+
                "2. Terry Fox began his Marathon of Hope in St. John's, NL, to raise money for cancer research.\n"
                + " The run ended on 1 September in Thunder Bay, ON, after cancer was discovered in his lungs. Within days the marathon had raised over $10 million.");
         }    else if (year.equals("1981")) {  
        OutputLabel.setText("Québec bans public signs in English");
         }    else if (year.equals("1982")) {  
        OutputLabel.setText("The Canadian Consitution, up until now British legislation, is ratified by the Canadian legislature and every provincial legislature, except Québec.");
         }    else if (year.equals("1983")) {  
        OutputLabel.setText("Jeanne Sauve is named the Governor General of Canada, the first woman appointed to this role.");
         }    else if (year.equals("1984")) {  
        OutputLabel.setText("Brian Mulroney of the Progressive Conservative party is first elected Prime Minister.");
         }    else if (year.equals("1985")) {  
        OutputLabel.setText("Nothing");
         }    else if (year.equals("1986")) {  
        OutputLabel.setText("Nothing");
         }    else if (year.equals("1987")) {  
        OutputLabel.setText("Nothing");
          }    else if (year.equals("1988")) { 
        OutputLabel.setText("Brian Mulroney runs for re-election and wins, the major issue being free trade with the United States.");
         }    else if (year.equals("1989")) {  
        OutputLabel.setText("Canada and the United States sign a free trade agreement.");
         }    else if (year.equals("1990")) {  
        OutputLabel.setText("The proposed Meech Lake Accord, a Constitutional proposal, fails.");
        }    else if (year.equals("1991")) {  
        OutputLabel.setText("On January 1st, the Goods and Services Tax (GST), the most unpopular tax in Canadian history is introduced.");
        }    else if (year.equals("1992")) {  
        OutputLabel.setText("The proposed Charlottetown Accord, a proposal for a new Canadian Constitution, is rejected in a referendum by just over half of Canadians.");
        }    else if (year.equals("1993")) {  
        OutputLabel.setText("Kim Campbell replaces the unpopular politician Brian Mulroney to become Canada’s first female Prime Minister.\n"+" In an election later that year her party loses all but 2 seats in a Jean Chretién election victory.");
        }    else if (year.equals("1994")) {  
        OutputLabel.setText("The North American Free Trade Agreement (NAFTA) came into effect, creating a free trade zone between Canada, the United States and Mexico.");
         }    else if (year.equals("1995")) {  
        OutputLabel.setText("Nothing");
         }    else if (year.equals("1996")) {  
        OutputLabel.setText("Nothing");
          }    else if (year.equals("1997")) {  
        OutputLabel.setText("Confederation Bridge links Prince Edward Island to the rest of Canada.");
      }    else if (year.equals("1996")) {  
        OutputLabel.setText("Nothing");
         }    else if (year.equals("1999")) {  
        OutputLabel.setText("The Territory of Nunavut is carved from the Northwest Territories\n" +
"on April 1st.");
        
       
   }
     
     
    }//GEN-LAST:event_SearchButtonActionPerformed

    private void yearInputLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearInputLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearInputLabelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(yearsandeventsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(yearsandeventsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(yearsandeventsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(yearsandeventsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new yearsandeventsGUI().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea OutputLabel;
    private javax.swing.JButton SearchButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private java.awt.Panel panel1;
    private javax.swing.JLabel reminder;
    private javax.swing.JTextField yearInputLabel;
    // End of variables declaration//GEN-END:variables
}
